"""분석 신고 이력 지원 저장"""

import sqlalchemy as sa
from alembic import op

revision = "b904fbf68671"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("input_method", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("transcript_raw", sa.Text(), nullable=True),
        sa.Column("content_suggested", sa.Text(), nullable=True),
        sa.Column("type_suggested", sa.String(length=16), nullable=True),
        sa.Column("urgency_suggested", sa.String(length=16), nullable=True),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_analyses_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_analyses_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analyses_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analyses_event_id"), ["event_id"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_final", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("type_value", sa.String(length=16), nullable=False),
        sa.Column("urgency_value", sa.String(length=16), nullable=False),
        sa.Column("type_source", sa.String(length=32), nullable=False),
        sa.Column("urgency_source", sa.String(length=32), nullable=False),
        sa.Column("type_confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("urgency_confirmed_by", sa.Uuid(), nullable=True),
        sa.Column("type_confirmed_at", sa.String(length=24), nullable=True),
        sa.Column("urgency_confirmed_at", sa.String(length=24), nullable=True),
        sa.Column("position", sa.JSON(), nullable=False),
        sa.Column("position_source", sa.String(length=16), nullable=False),
        sa.Column("zone", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(length=24), nullable=False),
        sa.Column("claimed_by", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.String(length=24), nullable=True),
        sa.Column("resolved_at", sa.String(length=24), nullable=True),
        sa.Column("resolve_note", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.String(length=24), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_reports_analysis_id_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["actors.id"], name=op.f("fk_reports_cancelled_by_actors")
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by"], ["actors.id"], name=op.f("fk_reports_claimed_by_actors")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_reports_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["actors.id"], name=op.f("fk_reports_reporter_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["type_confirmed_by"],
            ["actors.id"],
            name=op.f("fk_reports_type_confirmed_by_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["urgency_confirmed_by"],
            ["actors.id"],
            name=op.f("fk_reports_urgency_confirmed_by_actors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("analysis_id", name=op.f("uq_reports_analysis_id")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reports_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reports_reporter_id"), ["reporter_id"], unique=False
        )

    op.create_table(
        "report_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.String(length=24), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_report_logs_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_report_logs_report_id_reports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_logs")),
    )
    with op.batch_alter_table("report_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_logs_report_id"), ["report_id"], unique=False
        )

    op.create_table(
        "support_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column("opened_at", sa.String(length=24), nullable=False),
        sa.Column("closed_at", sa.String(length=24), nullable=True),
        sa.Column("close_reason", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["opened_by"],
            ["actors.id"],
            name=op.f("fk_support_requests_opened_by_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_support_requests_report_id_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_requests")),
    )
    with op.batch_alter_table("support_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_support_requests_report_id"), ["report_id"], unique=False
        )
        batch_op.create_index(
            "uq_active_support_report",
            ["report_id"],
            unique=True,
            sqlite_where=sa.text("closed_at IS NULL"),
            postgresql_where=sa.text("closed_at IS NULL"),
        )

    op.create_table(
        "participations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("support_request_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.String(length=24), nullable=False),
        sa.Column("ended_at", sa.String(length=24), nullable=True),
        sa.Column("end_reason", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_participations_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["support_request_id"],
            ["support_requests.id"],
            name=op.f("fk_participations_support_request_id_support_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participations")),
    )
    with op.batch_alter_table("participations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_participations_support_request_id"),
            ["support_request_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_active_participation_actor",
            ["support_request_id", "actor_id"],
            unique=True,
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_participation_actor",
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_participations_support_request_id"))

    op.drop_table("participations")
    with op.batch_alter_table("support_requests", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_support_report",
            sqlite_where=sa.text("closed_at IS NULL"),
            postgresql_where=sa.text("closed_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_support_requests_report_id"))

    op.drop_table("support_requests")
    with op.batch_alter_table("report_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_logs_report_id"))

    op.drop_table("report_logs")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_reporter_id"))
        batch_op.drop_index(batch_op.f("ix_reports_event_id"))
        batch_op.drop_index(batch_op.f("ix_reports_created_at"))

    op.drop_table("reports")
    with op.batch_alter_table("analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analyses_event_id"))
        batch_op.drop_index(batch_op.f("ix_analyses_actor_id"))

    op.drop_table("analyses")
    # ### end Alembic commands ###
